on:
  push:
    tags:
    - '*'

name: publish

jobs:
  default:
    name: Build Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PLATFORM: [android-30, android-29, android-28, android-27]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: carepaydev/android-sdk:${{ matrix.PLATFORM }}
        build-args: |
          PLATFORM=${{ matrix.PLATFORM }}
